# Assignment 1
Submission by:

> Darsh Kumar
> 
> 20BCE0301

## Initial Stage

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from keras import Sequential
from keras.layers import Dense
from keras.optimizers.legacy import adam

from sklearn.model_selection import train_test_split

2023-06-15 12:43:55.485021: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-15 12:43:56.065338: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
dataset = pd.read_csv('drug200.csv')
dataset.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [4]:
dataset.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

## Data Preprocessing Stage

### Handling Categorical Data

In [5]:
dataset.Sex = dataset.Sex.astype('category').cat.codes
dataset.BP = dataset.BP.astype('category').cat.codes
dataset.Cholesterol = dataset.Cholesterol.astype('category').cat.codes
dataset.head()

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   0            0   25.355  DrugY
1   47    1   1            0   13.093  drugC
2   47    1   1            0   10.114  drugC
3   28    0   2            0    7.798  drugX
4   61    0   1            0   18.043  DrugY

### Handling Empty Values


In [6]:
dataset.isna().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

There are no empty values, thus no further changes are required

### Training Testing Split


In [7]:
x = dataset.drop(['Drug'], axis = 1).values
y = pd.get_dummies(dataset.Drug).values
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.3)

print(xTrain.shape)
print(yTrain.shape)

xTrain[:5]

(140, 5)
(140, 5)


array([[31.   ,  1.   ,  0.   ,  1.   , 11.227],
       [68.   ,  1.   ,  0.   ,  0.   , 11.009],
       [58.   ,  0.   ,  0.   ,  1.   , 14.239],
       [53.   ,  1.   ,  2.   ,  0.   , 14.133],
       [72.   ,  0.   ,  1.   ,  1.   , 14.642]])

## Model Definition Stage

In [8]:
model = Sequential()
model.add(Dense(5, input_dim = 5, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(5, activation = 'softmax'))
model.compile(optimizer = adam.Adam(), loss = 'categorical_crossentropy', metrics = ['accuracy'])


2023-06-15 12:43:57.474049: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-15 12:43:57.516127: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-15 12:43:57.516194: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-15 12:43:57.518788: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:982] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-06-15 12:43:57.518885: I tensorflow/compile

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 30        
                                                                 
 dense_1 (Dense)             (None, 16)                96        
                                                                 
 dense_2 (Dense)             (None, 16)                272       
                                                                 
 dense_3 (Dense)             (None, 32)                544       
                                                                 
 dense_4 (Dense)             (None, 5)                 165       
                                                                 
Total params: 1,107
Trainable params: 1,107
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(xTrain, yTrain, epochs = 10)

Epoch 1/10
5/5 [==============================] - 2s 7ms/step - loss: 5.3161 - accuracy: 0.0714
Epoch 2/10
5/5 [==============================] - 0s 6ms/step - loss: 4.0593 - accuracy: 0.0929
Epoch 3/10
5/5 [==============================] - 0s 5ms/step - loss: 3.1802 - accuracy: 0.1500
Epoch 4/10
1/5 [=====>........................] - ETA: 0s - loss: 3.0587 - accuracy: 0.0938

2023-06-15 12:44:00.292928: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


5/5 [==============================] - 0s 6ms/step - loss: 2.5025 - accuracy: 0.1357
Epoch 5/10
5/5 [==============================] - 0s 5ms/step - loss: 1.9070 - accuracy: 0.2357
Epoch 6/10
5/5 [==============================] - 0s 6ms/step - loss: 1.4807 - accuracy: 0.3714
Epoch 7/10
5/5 [==============================] - 0s 6ms/step - loss: 1.2820 - accuracy: 0.4571
Epoch 8/10
5/5 [==============================] - 0s 6ms/step - loss: 1.2245 - accuracy: 0.5214
Epoch 9/10
5/5 [==============================] - 0s 5ms/step - loss: 1.1943 - accuracy: 0.5357
Epoch 10/10
5/5 [==============================] - 0s 6ms/step - loss: 1.1780 - accuracy: 0.5429


## Model Performance Stage

In [11]:
yPred = model.predict(xTest)

yPred[:5]

2/2 [==============================] - 0s 5ms/step


array([[0.4924729 , 0.09694248, 0.11270873, 0.06265338, 0.23522253],
       [0.27053234, 0.08037018, 0.0912785 , 0.13254768, 0.42527124],
       [0.88483924, 0.00738647, 0.08507465, 0.01021052, 0.01248901],
       [0.9500545 , 0.00130348, 0.04300205, 0.00258743, 0.00305261],
       [0.36268854, 0.10317911, 0.09301314, 0.07489836, 0.36622086]],
      dtype=float32)

In [12]:
yTest[:5]

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)